#List of ranks
[[ranks]]
	tier = 0
	numAffixes = 0
	defaultColor = "#FFFFFF"
	weight = 15000
	growthFactor = 1
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 1
	numAffixes = 1
	defaultColor = "#FFC0C8"
	weight = 1500
	growthFactor = 2
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 2
	numAffixes = 2
	defaultColor = "#4296A5"
	weight = 1200
	growthFactor = 4
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 3
	numAffixes = 3
	defaultColor = "#EAA55C"
	weight = 900
	growthFactor = 7
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 4
	numAffixes = 4
	defaultColor = "#EC78CA"
	weight = 700
	growthFactor = 11
	effects = []
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 5
	numAffixes = 5
	defaultColor = "#FFA000"
	weight = 600
	growthFactor = 16
	effects = ["minecraft:regeneration;1"]
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 6
	numAffixes = 6
	defaultColor = "#FF6692"
	weight = 500
	growthFactor = 22
	effects = ["minecraft:fire_resistance;1", "minecraft:regeneration;1"]
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 7
	numAffixes = 7
	defaultColor = "#FF66AA"
	weight = 300
	growthFactor = 28
	effects = ["minecraft:fire_resistance;1", "minecraft:regeneration;2"]
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 8
	numAffixes = 8
	defaultColor = "#C5B4B8"
	weight = 100
	growthFactor = 36
	effects = ["minecraft:fire_resistance;1", "minecraft:regeneration;2"]
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 9
	numAffixes = 10
	defaultColor = "#6A13AA"
	weight = 80
	growthFactor = 46
	effects = ["minecraft:fire_resistance;1", "minecraft:regeneration;3", "minecraft:resistance;1"]
	presetAffixes = []
#List of ranks
[[ranks]]
	tier = 10
	numAffixes = 12
	defaultColor = "#212801"
	weight = 50
	growthFactor = 60
	effects = ["minecraft:fire_resistance;1", "minecraft:regeneration;4", "minecraft:resistance;2"]
	presetAffixes = []
