# List of ranks
[[ranks]]
	tier = 0
	numAffixes = 0
	defaultColor = "#FFFFFF"
	weight = 10000
	growthFactor = 1
	effects = []
	presetAffixes = [
        "卢本伟",
        "小行星坠落",
        "林克",
        "特朗普",
        "张三",
        "李四",
        "王五",
        "老王",
        "谭先生",
        "班主任",
        "野兽先辈",
        "可可萝",
        "奥尔加",
        "莱德",
        "杰哥",
        "马库斯",
        "神灵吞噬者",
        "克苏鲁",
        "周树人",
        "杉斯",
        "川建国",
        "鲁智深",
        "曹操",
        "陶渊明",
        "动员兵",
        "李华",
        "UP主",
        "TCreopargh",
        "白嫖怪",
        "拿破仑",
        "蔡徐坤",
        "伏拉夫",
        "鸽子",
        "复读机",
        "马库斯",
        "李白",
        "乔拜登",
        "请输入昵称",
        "皮卡丘",
        "厂长",
        "达斯维达",
        "光头强"
    ]

[[ranks]]
    tier = 1
    numAffixes = 1
    defaultColor = "#FFC0C8"
    weight = 1500
    growthFactor = 2
    effects = []
    presetAffixes = [
        "卢本伟",
        "小行星坠落",
        "林克",
        "特朗普",
        "张三",
        "李四",
        "王五",
        "老王",
        "谭先生",
        "班主任",
        "野兽先辈",
        "可可萝",
        "奥尔加",
        "莱德",
        "杰哥",
        "马库斯",
        "神灵吞噬者",
        "克苏鲁",
        "周树人",
        "杉斯",
        "川建国",
        "鲁智深",
        "曹操",
        "陶渊明",
        "动员兵",
        "李华",
        "UP主",
        "TCreopargh",
        "白嫖怪",
        "拿破仑",
        "蔡徐坤",
        "伏拉夫",
        "鸽子",
        "复读机",
        "马库斯",
        "李白",
        "乔拜登",
        "请输入昵称",
        "皮卡丘",
        "厂长",
        "达斯维达",
        "光头强"
    ]

[[ranks]]
    tier = 2
    numAffixes = 2
    defaultColor = "#4296A5"
    weight = 1200
    growthFactor = 4
    effects = []
    presetAffixes = [
        "卢本伟",
        "小行星坠落",
        "林克",
        "特朗普",
        "张三",
        "李四",
        "王五",
        "老王",
        "谭先生",
        "班主任",
        "野兽先辈",
        "可可萝",
        "奥尔加",
        "莱德",
        "杰哥",
        "马库斯",
        "神灵吞噬者",
        "克苏鲁",
        "周树人",
        "杉斯",
        "川建国",
        "鲁智深",
        "曹操",
        "陶渊明",
        "动员兵",
        "李华",
        "UP主",
        "TCreopargh",
        "白嫖怪",
        "拿破仑",
        "蔡徐坤",
        "伏拉夫",
        "鸽子",
        "复读机",
        "马库斯",
        "李白",
        "乔拜登",
        "请输入昵称",
        "皮卡丘",
        "厂长",
        "达斯维达",
        "光头强"
    ]

[[ranks]]
    tier = 3
    numAffixes = 3
    defaultColor = "#EAA55C"
    weight = 900
    growthFactor = 7
    effects = []
    presetAffixes = [
        "卢本伟",
        "小行星坠落",
        "林克",
        "特朗普",
        "张三",
        "李四",
        "王五",
        "老王",
        "谭先生",
        "班主任",
        "野兽先辈",
        "可可萝",
        "奥尔加",
        "莱德",
        "杰哥",
        "马库斯",
        "神灵吞噬者",
        "克苏鲁",
        "周树人",
        "杉斯",
        "川建国",
        "鲁智深",
        "曹操",
        "陶渊明",
        "动员兵",
        "李华",
        "UP主",
        "TCreopargh",
        "白嫖怪",
        "拿破仑",
        "蔡徐坤",
        "伏拉夫",
        "鸽子",
        "复读机",
        "马库斯",
        "李白",
        "乔拜登",
        "请输入昵称",
        "皮卡丘",
        "厂长",
        "达斯维达",
        "光头强"
    ]

[[ranks]]
    tier = 4
    numAffixes = 4
    defaultColor = "#EC78CA"
    weight = 700
    growthFactor = 11
    effects = []
    presetAffixes = [
        "卢本伟",
        "小行星坠落",
        "林克",
        "特朗普",
        "张三",
        "李四",
        "王五",
        "老王",
        "谭先生",
        "班主任",
        "野兽先辈",
        "可可萝",
        "奥尔加",
        "莱德",
        "杰哥",
        "马库斯",
        "神灵吞噬者",
        "克苏鲁",
        "周树人",
        "杉斯",
        "川建国",
        "鲁智深",
        "曹操",
        "陶渊明",
        "动员兵",
        "李华",
        "UP主",
        "TCreopargh",
        "白嫖怪",
        "拿破仑",
        "蔡徐坤",
        "伏拉夫",
        "鸽子",
        "复读机",
        "马库斯",
        "李白",
        "乔拜登",
        "请输入昵称",
        "皮卡丘",
        "厂长",
        "达斯维达",
        "光头强"
    ]

[[ranks]]
    tier = 5
    numAffixes = 5
    defaultColor = "#FFA000"
    weight = 600
    growthFactor = 16
    effects = ["minecraft:regeneration;1"]
    presetAffixes = [
        "卢本伟",
        "小行星坠落",
        "林克",
        "特朗普",
        "张三",
        "李四",
        "王五",
        "老王",
        "谭先生",
        "班主任",
        "野兽先辈",
        "可可萝",
        "奥尔加",
        "莱德",
        "杰哥",
        "马库斯",
        "神灵吞噬者",
        "克苏鲁",
        "周树人",
        "杉斯",
        "川建国",
        "鲁智深",
        "曹操",
        "陶渊明",
        "动员兵",
        "李华",
        "UP主",
        "TCreopargh",
        "白嫖怪",
        "拿破仑",
        "蔡徐坤",
        "伏拉夫",
        "鸽子",
        "复读机",
        "马库斯",
        "李白",
        "乔拜登",
        "请输入昵称",
        "皮卡丘",
        "厂长",
        "达斯维达",
        "光头强"
    ]

[[ranks]]
    tier = 6
    numAffixes = 6
    defaultColor = "#FF6692"
    weight = 500
    growthFactor = 22
    effects = ["minecraft:fire_resistance;1", "minecraft:regeneration;1"]
    presetAffixes = [
        "卢本伟",
        "小行星坠落",
        "林克",
        "特朗普",
        "张三",
        "李四",
        "王五",
        "老王",
        "谭先生",
        "班主任",
        "野兽先辈",
        "可可萝",
        "奥尔加",
        "莱德",
        "杰哥",
        "马库斯",
        "神灵吞噬者",
        "克苏鲁",
        "周树人",
        "杉斯",
        "川建国",
        "鲁智深",
        "曹操",
        "陶渊明",
        "动员兵",
        "李华",
        "UP主",
        "TCreopargh",
        "白嫖怪",
        "拿破仑",
        "蔡徐坤",
        "伏拉夫",
        "鸽子",
        "复读机",
        "马库斯",
        "李白",
        "乔拜登",
        "请输入昵称",
        "皮卡丘",
        "厂长",
        "达斯维达",
        "光头强"
    ]

[[ranks]]
    tier = 7
    numAffixes = 7
    defaultColor = "#FF66AA"
    weight = 300
    growthFactor = 28
    effects = ["minecraft:fire_resistance;1", "minecraft:regeneration;2"]
    presetAffixes = [
        "卢本伟",
        "小行星坠落",
        "林克",
        "特朗普",
        "张三",
        "李四",
        "王五",
        "老王",
        "谭先生",
        "班主任",
        "野兽先辈",
        "可可萝",
        "奥尔加",
        "莱德",
        "杰哥",
        "马库斯",
        "神灵吞噬者",
        "克苏鲁",
        "周树人",
        "杉斯",
        "川建国",
        "鲁智深",
        "曹操",
        "陶渊明",
        "动员兵",
        "李华",
        "UP主",
        "TCreopargh",
        "白嫖怪",
        "拿破仑",
        "蔡徐坤",
        "伏拉夫",
        "鸽子",
        "复读机",
        "马库斯",
        "李白",
        "乔拜登",
        "请输入昵称",
        "皮卡丘",
        "厂长",
        "达斯维达",
        "光头强"
    ]

[[ranks]]
    tier = 8
    numAffixes = 8
    defaultColor = "#C5B4B8"
    weight = 100
    growthFactor = 36
    effects = ["minecraft:fire_resistance;1", "minecraft:regeneration;2"]
    presetAffixes = [
        "卢本伟",
        "小行星坠落",
        "林克",
        "特朗普",
        "张三",
        "李四",
        "王五",
        "老王",
        "谭先生",
        "班主任",
        "野兽先辈",
        "可可萝",
        "奥尔加",
        "莱德",
        "杰哥",
        "马库斯",
        "神灵吞噬者",
        "克苏鲁",
        "周树人",
        "杉斯",
        "川建国",
        "鲁智深",
        "曹操",
        "陶渊明",
        "动员兵",
        "李华",
        "UP主",
        "TCreopargh",
        "白嫖怪",
        "拿破仑",
        "蔡徐坤",
        "伏拉夫",
        "鸽子",
        "复读机",
        "马库斯",
        "李白",
        "乔拜登",
        "请输入昵称",
        "皮卡丘",
        "厂长",
        "达斯维达",
        "光头强"
    ]

[[ranks]]
    tier = 9
    numAffixes = 10
    defaultColor = "#6A13AA"
    weight = 80
    growthFactor = 46
    effects = ["minecraft:fire_resistance;1", "minecraft:regeneration;3", "minecraft:resistance;1"]
    presetAffixes = [
        "卢本伟",
        "小行星坠落",
        "林克",
        "特朗普",
        "张三",
        "李四",
        "王五",
        "老王",
        "谭先生",
        "班主任",
        "野兽先辈",
        "可可萝",
        "奥尔加",
        "莱德",
        "杰哥",
        "马库斯",
        "神灵吞噬者",
        "克苏鲁",
        "周树人",
        "杉斯",
        "川建国",
        "鲁智深",
        "曹操",
        "陶渊明",
        "动员兵",
        "李华",
        "UP主",
        "TCreopargh",
        "白嫖怪",
        "拿破仑",
        "蔡徐坤",
        "伏拉夫",
        "鸽子",
        "复读机",
        "马库斯",
        "李白",
        "乔拜登",
        "请输入昵称",
        "皮卡丘",
        "厂长",
        "达斯维达",
        "光头强"
    ]

[[ranks]]
    tier = 10
    numAffixes = 12
    defaultColor = "#212801"
    weight = 50
    growthFactor = 60
    effects = ["minecraft:fire_resistance;1", "minecraft:regeneration;4", "minecraft:resistance;2"]
    presetAffixes = [
        "卢本伟",
        "小行星坠落",
        "林克",
        "特朗普",
        "张三",
        "李四",
        "王五",
        "老王",
        "谭先生",
        "班主任",
        "野兽先辈",
        "可可萝",
        "奥尔加",
        "莱德",
        "杰哥",
        "马库斯",
        "神灵吞噬者",
        "克苏鲁",
        "周树人",
        "杉斯",
        "川建国",
        "鲁智深",
        "曹操",
        "陶渊明",
        "动员兵",
        "李华",
        "UP主",
        "TCreopargh",
        "白嫖怪",
        "拿破仑",
        "蔡徐坤",
        "伏拉夫",
        "鸽子",
        "复读机",
        "马库斯",
        "李白",
        "乔拜登",
        "请输入昵称",
        "皮卡丘",
        "厂长",
        "达斯维达",
        "光头强"
    ]
