#Minimum time in ticks for leaf decay. Must be lower than MaximumDecayTime!
# Default: 4
# Range: > 0
MinimumDecayTime = 2
#Maximum time in ticks for leaf decay. Must be higher than MinimumDecayTime!
# Default: 11
# Range: > 0
MaximumDecayTime = 8
