# Use Cloth Config mod for the descriptions.
---
snowGravity: true
snowMakingIce: true
snowAlwaysReplaceable: true
thinnerBoundingBox: true
snowNeverMelt: false
snowSpawnMaxLightLevel: 5
snowPersistMaxLightLevel: 8
snowReduceFallDamage: true
sustainGrassIfLayerMoreThanOne: true
sneakSnowball: true
fancySnowOnUpperSlab: true
rightClickToggleFancySnow: true
mobSpawningMaxLayers: 8
snow-cover:
  restoreOriginalBlocks: false
  replaceWorldgenFeature: true
  placeSnowOnBlock: true
  placeNaturally: true
accumulation:
  naturalMelting: true
  smoothAccumulation: true
  snowAndIceMeltInWarmBiomes: true
  maxLayers: 6
  accumulatesDuringSnowstorm: true
  accumulatesDuringSnowfall: false
integration:
  accumulationWinterOnly: false
debug:
  forceVanillaIceSnowLogic: false
  mobSpawningCommand: false
